# terraform.tfvars — staging environment
# Generated by platform-bot env setup. Do not edit manually on main.

aws_region         = "__AWS_REGION__"
cluster_name       = "__CLUSTER_NAME__"
environment        = "staging"
kubernetes_version = "1.33"
compliance_profile = "soc2"

log_retention_days = 14

aws_account_id = "__AWS_ACCOUNT_ID__"

github_org           = "__GITHUB_ORG__"
allowed_repos        = ["__ALLOWED_REPOS__"]
apply_branch_pattern = "dev"
