# terraform.tfvars — staging environment
# Generated by platform-bot env setup. Do not edit manually on main.

aws_region         = "eu-west-3"
cluster_name       = "dev-k8s"
environment        = "staging"
kubernetes_version = "1.33"
compliance_profile = "soc2"

log_retention_days = 14

aws_account_id = "351457945908"

github_org           = "PodYourLife"
allowed_repos        = ["k8s-platform"]
apply_branch_pattern = "dev"
