# Wave 6 — after prometheus (wave 4):
# ServiceMonitor CRD must exist before applying these resources

# This Application is intentionally minimal in the template — it covers
# the sample-app fixture used to validate the infra during bootstrap.
#
# When platform-bot onboards a new app with --monitor, it generates a
# ServiceMonitor manifest in kubernetes/manifests/<namespace>/servicemonitors/
# and commits it to the target repo. ArgoCD prune: true will pick it up
# automatically on the next sync — no changes needed here.
#
# Wave 6 — ServiceMonitor CRD must exist (prometheus wave 4) before this syncs
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-servicemonitors
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform

  source:
    repoURL: https://github.com/PodYourLife/k8s-platform.git
    targetRevision: __TARGET_REVISION__
    path: kubernetes/manifests/development/servicemonitors

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
