# Manages all cluster namespaces via GitOps
# Namespaces include PodSecurity labels and Istio injection labels
# Any namespace change must go through this Application — no manual kubectl create namespace
#
# Wave -3 — must sync before everything else:
# monitoring-namespace carries istio-injection: disabled
# If prometheus syncs before this, Jobs will get sidecars and block indefinitely
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: platform

  source:
    repoURL: https://github.com/PodYourLife/k8s-platform.git
    targetRevision: HEAD
    path: kubernetes/namespaces

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
