apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smoke-app-secrets
  namespace: development
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: smoke-app-secrets
  data: []  # TODO: add secret keys
