# terraform.tfvars — dev environment
# Generated by platform-bot env setup. Do not edit manually on main.
# All values below are __PLACEHOLDER__ tokens resolved at env setup time.

aws_region         = "eu-west-3"
cluster_name       = "dev-k8s"
environment        = "dev"
kubernetes_version = "1.33"
compliance_profile = "none"

log_retention_days = 7

aws_account_id = "351457945908"

github_org           = "PodYourLife"
allowed_repos        = ["k8s-platform"]
apply_branch_pattern = "dev"
