# terraform.tfvars — dev environment
# Generated by platform-bot env setup. Do not edit manually on main.
# All values below are __PLACEHOLDER__ tokens resolved at env setup time.

aws_region         = "__AWS_REGION__"
cluster_name       = "__CLUSTER_NAME__"
environment        = "dev"
kubernetes_version = "__KUBERNETES_VERSION__"
compliance_profile = "none"

log_retention_days = 7

aws_account_id = "__AWS_ACCOUNT_ID__"

github_org    = "__GITHUB_ORG__"
allowed_repos = ["__ALLOWED_REPOS__"]
