apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Name }}
  endpoints:
    - port: http
      path: /metrics
