{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ml-batch-job.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "ml-batch-job.labels" . | nindent 4 }}
    # release: prometheus label is required for the kube-prometheus-stack
    # ServiceMonitor discovery. Without it, Prometheus ignores this resource.
    release: prometheus
spec:
  selector:
    matchLabels:
      {{- include "ml-batch-job.selectorLabels" . | nindent 6 }}
      ml-platform/job-type: cpu-train
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
{{- end }}
