# ClusterSecretStore — global AWS Secrets Manager backend
# Used by all ExternalSecret resources across namespaces
# IRSA role is provisioned by Terraform and injected by platform-bot
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: __AWS_REGION__
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
