# Installs Loki — log aggregation backend for Grafana
# Receives logs from Promtail agents running on each node
# Values file: kubernetes/helm/monitoring/loki-values.yaml
#
# Wave 5 — after prometheus (wave 4):
# monitoring.coreos.com CRDs installed by prometheus must exist
# before ServiceMonitors for Loki can be applied
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.53.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/kubernetes/helm/monitoring/loki-values.yaml
    - repoURL: https://github.com/PodYourLife/k8s-platform.git
      targetRevision: local-test
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
