# Installs Promtail — DaemonSet that ships pod logs to Loki
# Runs on every node, tails /var/log/pods and forwards to Loki
# Values file: kubernetes/helm/monitoring/promtail-values.yaml
#
# Wave 5 — after prometheus (wave 4), same wave as loki
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.17.1
      helm:
        releaseName: promtail
        valueFiles:
          - $values/kubernetes/helm/monitoring/promtail-values.yaml
    - repoURL: https://github.com/PodYourLife/k8s-platform.git
      targetRevision: __TARGET_REVISION__
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
