# Deploys ServiceMonitors and PodMonitors for the monitoring namespace
# Covers: Loki, Promtail, Istio proxies (PodMonitor), Istio control plane
# Prometheus discovers these via its serviceMonitorNamespaceSelector: any: true config
# label release: prometheus must match the Prometheus operator selector
#
# Wave 6 — after prometheus + loki + promtail (wave 4-5):
# ServiceMonitor CRD (monitoring.coreos.com) must exist before applying these resources
# Loki and Promtail pods must exist for ServiceMonitors to resolve their selectors
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-servicemonitors
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: platform

  source:
    repoURL: https://github.com/PodYourLife/k8s-platform.git
    targetRevision: HEAD
    path: kubernetes/manifests/monitoring/servicemonitors

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
