apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lpcdm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/PodYourLife/k8s-platform.git
    targetRevision: HEAD
    path: kubernetes/helm/sample-app
    helm:
      valueFiles:
        - ../../helm/values/lpcdm.yaml
      parameters:
        - name: image.tag
          value: "latest"

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

