# Installs the Istio ingress gateway
# Entry point for all external traffic into the mesh
# Depends on: istiod
#
# Default service type: LoadBalancer
# Minikube: run 'minikube tunnel' to get an external IP
# EKS/GKE: cloud NLB provisioned automatically — no config needed
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform

  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.26.4
    helm:
      releaseName: istio-ingressgateway

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true