# Installs the Istio ingress gateway
# Entry point for all external traffic into the mesh
# NodePort is used for local Minikube — change to LoadBalancer for cloud
# Depends on: istiod
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Deploys after istiod is ready
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.26.0
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          # NodePort for Minikube — use LoadBalancer on EKS/GKE
          type: NodePort

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
