# Installs the Istio ingress gateway
# Entry point for all external traffic into the mesh
# Depends on: istiod
#
# Minikube: run 'minikube tunnel' to expose the LoadBalancer IP
# EKS/GKE: LoadBalancer provisions a cloud NLB automatically
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.26.0
      helm:
        releaseName: istio-ingressgateway
        valueFiles:
          - - $values/istio/helm/gateway-values.yaml
    - repoURL: https://github.com/PodYourLife/k8s-platform.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true