apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: development-permissive-probes
  namespace: development
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    8080:
      mode: PERMISSIVE