---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB+3cf9rrutx0zvRxM2Txftkx2jPk4nxxVEz6n74CwTJ8N7OAgodcLGjrLKt74j89C65pLb1soeoMu2suz238juM6nENOcGl515bQiky+zDCcRtOC/fiqDRFiQMaw5uL6O5x+fhs7hJr1vdH7GJXwbS3sHuhQ2+Z/g0SZ1ta6HFwm7/xVQwR1230f+reyfGOZRv2nYa7GcMc9/FDb4yaKqG4VgWg+i5I3yJ28yZJIBpOqjJrNSK7qzC1Q+Y+K4EvfnlJJVCC9k2f30iXRlSkyuLr5tNob5Q9pSWGlfKBTTNgWtTT41/382BUZQ7HYBgooyi9zH7g683VLf1aS70poLfvJCaW6gN/LMABNtFZqTkbuM+7dioliE7dp+JK0lv4342DADdyE1XI61W50I9pc+IRuXBkP0MFAWnAnPcESeN4cUu3JItedj8hvmRK8uin3yYR3ia6C6fC0SQb6adbKNx6g1frOjM/WxVV11vKUlUSjdpcL7S63CxKH79yrMiQ5Cokqty1PE6V/RVGwBBTEkLOT6KubqxbLeMUbAbEXTI+30wdOsVU7RPFNl6wmQrzJcNSIkZHnbjFKIl0hsAfNlxKHM/2qeiz0gvLfmKyX8rEJdGns7a/yJsEklBbhCjF8OLujyxs7fSYlux4O35WJOcboAjmCOqIyKT9JbveHTdd7UOxej8A/q642H3x8osku6PM8qM1O3K+A==
    admin-user: AgADdNoa5eLz2hzRgHkr3ndoYUIv2i8Nf6j103qq3Cz1x8QpT0vOBRJ2RrTDRroAa1vRaASItVih9aP+bzfUmxA6WsLQBWYViy/6sZUX+p+iR8c39v+FrXmGOgVdsdLvdcQ0h6gDtxWNR7MwqoofDl1U+LIM0CZ03KF/ytm24vbm7CJZe3xDPEgSlf5lGcd422TKEwIWNrxzHchTEuoEEGRcwvXcUmKWB/pDk07fHWc2fy6bTrAqeka0mdi5vQv4B7/n+3IKdmx0wAAHSjIeMHtW7HL3IjVBcwfshMlb6P8nASBKKyykWHu7SRXfwBzDQz1A8iqxEeLW4mgOKB+lDPTsJ7xbh+rGo+2ja9RC0IHLHOQVExTFqW2RL8aKWhoykQkztPimsznlwZluBllSDyTlEvPlKlzAHOLyjquWiTzK5MoolKYJC9ffMqSDkLd2L+KZIQKoMFK5zdC9nsTJSTZPDFAKB/4qXub91kgduvXyjE55vc3+Yc2MI0eop7hVYs9muo2P7NCMDW0EDrh3cjXKxOiFM8XKDyI/C+L6z3P0Ooql81c5TSKyA+htNb/tDiezIqErXmzlBkA4NrIZzPo2oJmz9RjTR2AWVjqeUbWegA3Hplp+Qm4iVrfIRmtgYBLE3OIn7g8TG9FHdibnSvQo9KX3nNksfYkSUDHg9Fq3PIQkpeWIFUG596wRpKpWKuqc/+zoBA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
